### ISSUE TITLE
mysql断开连接后一些问题

### ISSUE THREAD

**Issue by ronalfei** [swoole/mysql-async#1]
如果送mysqld断开连接,  会触发onSQLReady事件,  因为不是正常的事件,  会导致:$this->work_pool[$db_sock] 为空,  从而导致 $mysqli->reap_async_query() fatalerror.

我修改了代码如下后:
$task = empty($this->work_pool[$db_sock])?Null:$this->work_pool[$db_sock];
        if(empty($task)){
            echo "MySQLi Warning: Maybe SQLReady receive a Close event , such as mysql server close the socket !\n";
            unset($this->work_pool[$db_sock]);
            return false;
        }
发现这个事件会不断的被促发, 因此输出很多echo信息.

**Comment by matyhtf** [comment]
建议提交一下PR。
MySQL关闭后，应当使用swoole_event_del从事件循环中移除，并执行一次mysqli_close，然后从pool中unset.

**Comment by ronalfei** [comment]
这个问题已经合并相关PR, 我关闭了吧.
